language: c

sudo: false
os: linux-ppc64le

addons:
  apt:
    packages:
    - autopoint
    - libuv-dev 
    - libdevmapper-dev 
    - flex
    - bison
    
before_install:
  #-  sudo apt-get -qq update
  #-  sudo apt-get install -y autopoint libuv-dev libdevmapper-dev flex bison
  -  ./bootstrap

install:
  - ./configure --with-twin-x11=no --with-twin-fbdev=no
  - make

script:
  - make check
