language: c

sudo: false
os: linux-ppc64le
dist: xenial

addons:
  apt:
    packages:
      - git


#addons:
#  apt:
#    packages:
#    - autopoint
#    - libuv-dev 
#    - libdevmapper-dev 
#    - flex
#    - bison
    
before_install: skip
  # -  ./bootstrap

install: skip 
  #- ./configure --with-twin-x11=no --with-twin-fbdev=no
 # - make

script: skip
  #- make check
