language: c
os: linux-ppc64le
sudo: required
dist: xenial

before_install:
  - travis_retry sudo apt-get -qq update
  - travis_retry sudo apt-get install -y autopoint libuv-dev libdevmapper-dev flex bison
  - ./bootstrap

install:
  - ./configure --with-twin-x11=no --with-twin-fbdev=no
  - make

script:
  - make check
