language: c

sudo: false
os: linux-ppc64le
dist: xenial

addons:
  apt:
    update: true
    packages:
    - autopoint
    - libuv-dev 
    - libdevmapper-dev 
    - flex
    - bison
    
before_install:
  -  ./bootstrap

install:
  - ./configure --with-twin-x11=no --with-twin-fbdev=no
  - make

script:
  - make check
