language: c
os:
  - linux-ppc64le
  - linux

sudo: false
dist: xenial

before_install:
 - apt-get -qq update
 - apt-get install -y autopoint libuv-dev libdevmapper-dev flex bison
 - ./bootstrap

install:
 - ./configure --with-twin-x11=no --with-twin-fbdev=no
 - make

script:
 - make check
